### ISSUE TITLE
Sequence of project back and final FC layer

### ISSUE THREAD

**Issue by ShuaiWang97** [ycq091044/Hypergraph-Learning-with-Line-Expansion#3]
Hi Chaoqi,

Thanks for the great work. In the README I see that you first project back to hypergraph domain then use a FC layer to predict label. However, in the model.py code, you direct use the project back embedding for prediction. I want to ask do you think the final FC layer is necessary based on you experience?

```
# prepare your ```DATASET-NAME.content``` and get features as well as the labels
features, labels = content[:, 1:-1], content[:, -1]

# project features into LE domain
features = Pv @ features

# get embedding in LE graph domain
embedding = run_graph_algorithm(adj, features)

# project back to hypergraph domain
embedding_back = PvT @ embedding

# use FC layer to predict label
class_logit = fully_connected_layer(embedding_back)
```

Best,
Shaui

**Comment by ycq091044** [comment]
Hi @ShuaiWang97, thanks for the finding! I did not realize that I missed the FC layer in the `model.py`.

In my opinion, I feel adding the final FC layer or not will not affect significantly the overall performance, and the discussion of "whether we should add a final FC layer" is beyond the main point of the paper. From the design point of view, I would prefer to add the FC layer.

**Comment by ShuaiWang97** [comment]
I see. Thanks!
